version: "3"
services:
  nuxt:
    container_name: nuxt
    build: ./docker/js
    volumes:
    - ./nuxt:/nuxt
    environment:
      - HOST=0.0.0.0
    ports:
      - "3000:3000"
    command: yarn dev
  python:
    build: ./docker/python
    volumes:
      - ./server:/server
    tty: true
    stdin_open: true
    ports:
      - "8000:8000"
    command: python3 myblog/manage.py runserver 0.0.0.0:8000
