version: "3"
services:
  nuxt:
    container_name: nuxt
    build: ./docker/js
    command: yarn dev
    volumes: 
    - ./nuxt:/nuxt
    ports: 
      - "3000:3000"
      - "9229:9229"
  db:
    image: postgres:10
  python:
    build: ./docker/python
    volumes:
      - ./server:/server
    tty: true
    ports:
      - 8000:8000
    depends_on:
      - db